In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## Define the vocabulary size
voc_size = 10000

In [9]:
## One Hot Representation
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr

[[2557, 311, 3244, 7284],
 [2557, 311, 3244, 1255],
 [2557, 1144, 3244, 4623],
 [5151, 5159, 6555, 7144, 4247],
 [5151, 5159, 6555, 7144, 1057],
 [3499, 2557, 2161, 3244, 5427],
 [4501, 4395, 6300, 7144]]

In [10]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## we will setup a maximum sentence length using pad_sequence. We make sure that all the sentences are of equal legth.
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2557  311 3244 7284]
 [   0    0    0    0 2557  311 3244 1255]
 [   0    0    0    0 2557 1144 3244 4623]
 [   0    0    0 5151 5159 6555 7144 4247]
 [   0    0    0 5151 5159 6555 7144 1057]
 [   0    0    0 3499 2557 2161 3244 5427]
 [   0    0    0    0 4501 4395 6300 7144]]


In [26]:
## Feature Representation
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [30]:
model.predict(embedded_docs)
## Every word is represented by 10 dimension


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[-0.03880546,  0.04372199, -0.02992812,  0.03397061,
          0.01280591, -0.04808852, -0.0415148 ,  0.01157992,
         -0.049657  , -0.03687515],
        [-0.03880546,  0.04372199, -0.02992812,  0.03397061,
          0.01280591, -0.04808852, -0.0415148 ,  0.01157992,
         -0.049657  , -0.03687515],
        [-0.03880546,  0.04372199, -0.02992812,  0.03397061,
          0.01280591, -0.04808852, -0.0415148 ,  0.01157992,
         -0.049657  , -0.03687515],
        [-0.03880546,  0.04372199, -0.02992812,  0.03397061,
          0.01280591, -0.04808852, -0.0415148 ,  0.01157992,
         -0.049657  , -0.03687515],
        [ 0.03888309,  0.04705397, -0.04063016, -0.04819497,
          0.03461579,  0.02356312,  0.02245713,  0.01313901,
          0.0411895 ,  0.02313713],
        [-0.04558175, -0.0444695 , -0.0097429 , -0.04782077,
         -0.03220759,  0.01717087, -0.00897191,  0.01879262,
          0.03070435, -0.0001993 ],
        [-0.02814394,  0.01810945, -0.00774642, -0.0

In [31]:
embedded_docs[0]

array([   0,    0,    0,    0, 2557,  311, 3244, 7284], dtype=int32)

In [32]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[-0.03880546  0.04372199 -0.02992812  0.03397061  0.01280591 -0.04808852
  -0.0415148   0.01157992 -0.049657   -0.03687515]
 [-0.03880546  0.04372199 -0.02992812  0.03397061  0.01280591 -0.04808852
  -0.0415148   0.01157992 -0.049657   -0.03687515]
 [-0.03880546  0.04372199 -0.02992812  0.03397061  0.01280591 -0.04808852
  -0.0415148   0.01157992 -0.049657   -0.03687515]
 [-0.03880546  0.04372199 -0.02992812  0.03397061  0.01280591 -0.04808852
  -0.0415148   0.01157992 -0.049657   -0.03687515]
 [ 0.03888309  0.04705397 -0.04063016 -0.04819497  0.03461579  0.02356312
   0.02245713  0.01313901  0.0411895   0.02313713]
 [-0.04558175 -0.0444695  -0.0097429  -0.04782077 -0.03220759  0.01717087
  -0.00897191  0.01879262  0.03070435 -0.0001993 ]
 [-0.02814394  0.01810945 -0.00774642 -0.01362959 -0.04859657  0.01201943
  -0.04106472 -0.02577852  0.01452197  0.0289426 ]
 [-0.04555481  0.04766851 -0.03502063  0.03616282  0.02351173 -0.00934707
  -0.01155351

In [29]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)