# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
# arange
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
# zeros and ones
# generate arrays of zeros and ones
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# linspace
# Return evenly spaced numbers over a specified interval.

np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [17]:
np.linspace(0,5,50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [18]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [19]:
# eye
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
# random
# Generate random numbers

np.random.rand(5)

array([0.18906252, 0.792422  , 0.51411889, 0.62652298, 0.47254665])

In [22]:
np.random.rand(10)

array([0.0525481 , 0.14419872, 0.46800892, 0.38729129, 0.42956878,
       0.06996974, 0.8801244 , 0.96729318, 0.08003647, 0.84889178])

In [23]:
np.random.rand(5,5)

array([[0.77321773, 0.41873181, 0.5722728 , 0.39221412, 0.21490611],
       [0.97924801, 0.76120445, 0.05630977, 0.19610947, 0.08089194],
       [0.46429916, 0.92683456, 0.19817661, 0.95161589, 0.80311516],
       [0.57012554, 0.04358526, 0.82943114, 0.01577247, 0.65006098],
       [0.83878081, 0.54730304, 0.92840329, 0.57880274, 0.80637314]])

In [26]:
np.random.randn(2)

array([-0.47705888,  0.59027796])

In [27]:
np.random.randn(5)

array([ 0.82534464,  0.19080615, -1.02277321, -0.52325997,  0.06454441])

In [29]:
np.random.randn(5,5)

array([[-0.64751776, -0.25677618, -1.82627067,  0.80402838, -1.30642302],
       [ 0.1579112 ,  0.67878527, -1.05885855, -1.71637222,  1.16298558],
       [ 0.08994457,  0.59292957,  0.10026574,  0.03605076, -0.57250591],
       [ 0.05879791, -0.81202271, -1.23457714, -2.4661325 , -0.68047618],
       [-0.54443733, -0.72225744, -0.79129416,  2.11553001,  2.34543081]])

In [ ]:
# random integer between 1 and exclusive100
np.random.randint(1,100)

50

In [32]:
# random integer between 1 and exclusive 100 and need 10 of them
np.random.randint(1,100,10)

array([97, 81, 12, 68, 64, 26, 86, 60, 69, 81], dtype=int32)

In [34]:
# reshape
# return an array containing the same data with a new shape.
arr = np.arange(0,25)
print(arr)
arr.reshape(5,5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.max()

np.int64(24)

In [36]:
arr.min()

np.int64(0)

In [37]:
ranarr = np.random.randint(1,100,10)
ranarr

array([ 8, 62, 43, 95, 76, 86, 31, 16, 14, 38], dtype=int32)

In [38]:
print(ranarr.max())
print(ranarr.min())

95
8


In [39]:
# argmax and argmin are used to find the index of the maximum and minimum values in an array.
print(ranarr.argmax())
print(ranarr.argmin())

3
0


In [40]:
from numpy.random import randint
randint(2,10)

9