# Numpy Indexing and Selection

In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
print(arr[8])
print(arr[1:5])
print(arr[0:5])
print(arr[:6])
print(arr[5:])
print(arr[4:8])

8
[1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4 5]
[ 5  6  7  8  9 10]
[4 5 6 7]


In [5]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
arr =np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
# original array also changed because slice_of_arr is a view of arr not a copy
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
# Indexing a 2D array (matrix)
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
print(arr_2d[0]) # first row
print(arr_2d[1]) # second row
print(arr_2d[2]) # third row

print(arr_2d[0][0]) # first row, first column
print(arr_2d[0][1]) # first row, second column
print(arr_2d[1][1]) # second row, second column
print(arr_2d[2][0]) # third row, first column
print(arr_2d[2,2]) # third row, third column

[ 5 10 15]
[20 25 30]
[35 40 45]
5
10
25
35
45


In [18]:
# we can use , instead of [][] to access elements in a 2D array

print(arr_2d[0,0]) # first row, first column
print(arr_2d[0,1]) # first row, second column
print(arr_2d[1,1]) # second row, second column
print(arr_2d[2,0]) # third row, first column
print(arr_2d[2,2]) # third row, third column

5
10
25
35
45


In [19]:
# return 10,15 and 25,30
print(arr_2d[:2,1:])

[[10 15]
 [25 30]]


In [ ]:
print(arr_2d[:1])
print(arr_2d[:2])
print(arr_2d[:3])

[[ 5 10 15]]
[[ 5 10 15]
 [20 25 30]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [25]:
print(arr_2d[:3,2:])

[[15]
 [30]
 [45]]


In [26]:
print(arr_2d[:3,:])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [30]:
# print last 2 rows
print(arr_2d[1:3,:])

[[20 25 30]
 [35 40 45]]


In [35]:
arr = np.arange(1,11)
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [37]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [39]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [40]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])